#' Exercício 04-twitter
#' Nome do aluno: 

library(tidyverse)
library(httr)

# me ----------------------------------------------------------------------

library(rtweet)

get_tokens()

trends <- rtweet::get_trends()
dplyr::glimpse(trends)

# us ----------------------------------------------------------------------

# 1. Vamos tuitar!
rtweet::post_tweet("Estou tuitando no Workshop de Web Scraping I da @curso_r, usando o pacote rtweet do #rstats")

# you ---------------------------------------------------------------------

# 1. faça rodar tab_twitter <- rtweet::get_my_timeline()

# 2. Rode tibble::glimpse(dplyr::select(tab_twitter, 1:20), 80)
## e cole o resultado abaixo. Deixe o resultado como um comentário
## Dica: Selecione as linhas que deseja comentar e aplique Ctrl+Shift+C

# Observations: 98
# Variables: 20
# $ user_id              <chr> "27933445", "27933445", "771137229049753600", "6…
# $ status_id            <chr> "1244016107331235841", "1244015429187784705", "1…
# $ created_at           <dttm> 2020-03-28 21:38:47, 2020-03-28 21:36:05, 2020-…
# $ screen_name          <chr> "rogerioneiva", "rogerioneiva", "RafaelLuizLemos…
# $ text                 <chr> "Não estou entendo! O chefe do Min da Saúde não …
# $ source               <chr> "Twitter for iPhone", "Twitter for iPhone", "Twi…
# $ display_text_width   <dbl> 118, 134, 76, 140, 260, 279, 280, 67, 280, 268, …
# $ reply_to_status_id   <chr> NA, NA, NA, NA, NA, NA, NA, NA, "124398669516028…
# $ reply_to_user_id     <chr> NA, NA, NA, NA, NA, NA, NA, NA, "37717107", "377…
# $ reply_to_screen_name <chr> NA, NA, NA, NA, NA, NA, NA, NA, "minsaude", "min…
# $ is_quote             <lgl> TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, …
# $ is_retweet           <lgl> FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, F…
# $ favorite_count       <int> 0, 0, 0, 0, 457, 443, 1019, 442, 437, 424, 496, …
# $ retweet_count        <int> 0, 2730, 0, 1973, 75, 105, 427, 147, 96, 84, 98,…
# $ quote_count          <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
# $ reply_count          <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
# $ hashtags             <list> [NA, NA, <"COVIDー19", "coronavirusnobrasil", "N…
# $ symbols              <list> [NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
# $ urls_url             <list> ["twitter.com/exilado/status…", NA, NA, NA, NA,…
# $ urls_t.co            <list> ["https://t.co/o42r8NdBpf", NA, NA, NA, NA, "ht…

# 2. [extra] faça a tabela do dashboard do slide 09, usando reactable::reactable()

reactable::reactable(tab_twitter[,1:5])
